-- ProjNav VHDL simulation template: tbw_subb_flagZ_setM.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
